train:
    _target_: shapeft.engine.data_preprocessor.Preprocessor
    preprocessor_cfg:
        - _target_: shapeft.engine.data_preprocessor.RandomCropToEncoder
        - _target_: shapeft.engine.data_preprocessor.BandFilter
        - _target_: shapeft.engine.data_preprocessor.NormalizeMeanStd
        - _target_: shapeft.engine.data_preprocessor.BandPadding

val:
    _target_: shapeft.engine.data_preprocessor.Preprocessor
    preprocessor_cfg:
        - _target_: shapeft.engine.data_preprocessor.BandFilter
        - _target_: shapeft.engine.data_preprocessor.NormalizeMeanStd
        - _target_: shapeft.engine.data_preprocessor.BandPadding

test:
    _target_: shapeft.engine.data_preprocessor.Preprocessor
    preprocessor_cfg:
        - _target_: shapeft.engine.data_preprocessor.BandFilter
        - _target_: shapeft.engine.data_preprocessor.NormalizeMeanStd
        - _target_: shapeft.engine.data_preprocessor.BandPadding