train: false
pretrain: false
work_dir: ""
seed: 234
use_wandb: false
wandb_project: ""

# TRAINING
num_workers: 1
batch_size: 8


# EXPERIMENT
use_final_ckpt: false
finetune: false
ckpt_dir: ???


defaults:
  - task: ???
  - _self_ 
