_target_:  shapeft.encoders.utae_encoder.UTAE_Encoder
encoder_weights: null
download_url: null
input_size: ${dataset.img_size}
multi_temporal: ${dataset.multi_temporal}
topology: [64, 64, 64, 128]

input_bands: ${dataset.bands}

output_dim:
  - 64
  - 64
  - 64
  - 128

